name: nexa_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Ícones
  cupertino_icons: ^1.0.8

  # Máscara de campos
  mask_text_input_formatter: ^2.9.0

  # Leitura de texto
  flutter_tts: ^3.8.5

  # Requisições HTTP
  http: ^1.2.2

  # Gerenciamento de estado
  provider: ^6.0.5

  # Abrir links
  url_launcher: ^6.2.5

  # Reprodução de vídeos
  video_player: ^2.9.5

  # Câmera
  camera: ^0.11.0+2

  # Permissões do sistema
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/bruno.png
    - assets/erik.png
    - assets/fernanda.png
    - assets/laura.png
    - assets/livia.png
    - assets/logo.nexa.png
    - assets/logo_branco.png
    - assets/funci.png
    - assets/funci.webp
    - assets/nicoly.png
    - assets/ryan.jpg
    - assets/slide1.jpg
    - assets/slide2.jpg
    - assets/fundo.jpg
    - assets/slide3.jpg
    - assets/model.tflite
    - assets/labels.txt
    - assets/escuro.png
    - assets/epi_construcao_1.mp4
    - assets/epi_construcao_2.mp4
    - assets/epi_construcao_3.mp4
    - assets/epi_construcao_4.mp4