CREATE DATABASE IF NOT EXISTS BD_NEXA;
USE BD_NEXA;

TRUNCATE TABLE OCORRENCIA;


CREATE TABLE IF NOT EXISTS EMPRESA (
    CNPJ VARCHAR(18) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    RUA VARCHAR(100) NOT NULL,
    CEP VARCHAR(20) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS SETOR (
    ID INT PRIMARY KEY AUTO_INCREMENT ,
    NOME VARCHAR(100) NOT NULL,
    LOCAL VARCHAR(100) NOT NULL,
    FK_CNPJ_EMPRESA VARCHAR(18)NOT NULL,
    FOREIGN KEY (FK_CNPJ_EMPRESA) REFERENCES EMPRESA(CNPJ) ON DELETE CASCADE
);

select * from camera;

CREATE TABLE IF NOT EXISTS ADMINISTRADOR (
    CPF VARCHAR(14) PRIMARY KEY NOT NULL,
    NOME_COMPLETO VARCHAR(120) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    EMAIL_CORPORATIVO VARCHAR(120) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    FK_CNPJ_EMPRESA VARCHAR(18) NOT NULL,
    FOREIGN KEY (FK_CNPJ_EMPRESA) REFERENCES EMPRESA(CNPJ) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CAMERA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    STATUS VARCHAR(20) NOT NULL,
    IDENTIFICADOR_CAMERA VARCHAR(20) NOT NULL,
    FK_CNPJ_EMPRESA VARCHAR(18) NOT NULL,
    FK_ID_SETOR INT,
    FOREIGN KEY (FK_CNPJ_EMPRESA) REFERENCES EMPRESA(CNPJ) ON DELETE CASCADE,
    FOREIGN KEY (FK_ID_SETOR) REFERENCES SETOR(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CAM_ADM(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    FK_ID_CAMERA INT,
    FK_CPF_ADMINISTRADOR VARCHAR (14),
    FOREIGN KEY (FK_ID_CAMERA) REFERENCES CAMERA(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_ADMINISTRADOR) REFERENCES ADMINISTRADOR(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO (
    CPF VARCHAR(14) PRIMARY KEY,
    NOME_COMPLETO VARCHAR(120) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    EMAIL_CORPORATIVO VARCHAR(120) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    UID_RFID VARCHAR(50) NOT NULL,
    FK_CNPJ_EMPRESA VARCHAR(18)NOT NULL,
    FK_ID_SETOR INT,
    FOREIGN KEY (FK_CNPJ_EMPRESA) REFERENCES EMPRESA(CNPJ) ON DELETE CASCADE,
    FOREIGN KEY (FK_ID_SETOR) REFERENCES SETOR(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EPI (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME_EPI VARCHAR(100) NOT NULL,
    IMAGEM_EPI VARCHAR(100) NOT NULL,
    DESCRICAO_EPI TEXT
);

CREATE TABLE IF NOT EXISTS OCORRENCIA (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    DATA_ANALISE DATE NOT NULL,
    HORA_ANALISE TIME NOT NULL,
    EPIS_DETECTADOS VARCHAR(200) NOT NULL,
    EPIS_AUSENTE VARCHAR(200) NOT NULL,
    STATUS_OCORRENCIA VARCHAR(50) NOT NULL,
    FK_ID_CAMERA INT,
    FOREIGN KEY (FK_ID_CAMERA) REFERENCES CAMERA(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FUN_OCORRENCIA (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FK_FUNCIONARIO_CPF VARCHAR(14) NOT NULL,
    FK_ID_OCORRENCIA INT,
    FOREIGN KEY (FK_FUNCIONARIO_CPF) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE,
    FOREIGN KEY (FK_ID_OCORRENCIA) REFERENCES OCORRENCIA(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS OCORRENCIA_EPI (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FK_OCORRENCIA_ID INT NOT NULL,
    FK_EPI_ID INT,
    FOREIGN KEY (FK_OCORRENCIA_ID) REFERENCES OCORRENCIA(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_EPI_ID) REFERENCES EPI(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EPI_ADM (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FK_EPI_ADM INT NOT NULL,
    FK_ADMINISTRADOR_CPF VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_EPI_ADM) REFERENCES EPI(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_ADMINISTRADOR_CPF) REFERENCES ADMINISTRADOR(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FUN_ADM (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FK_FUNCIONARIO_CPF VARCHAR(14) NOT NULL,
    FK_ADMINISTRADOR_CPF VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_FUNCIONARIO_CPF) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE,
    FOREIGN KEY (FK_ADMINISTRADOR_CPF) REFERENCES ADMINISTRADOR(CPF) ON DELETE CASCADE
);




-- TABELA CRIADA NO DIA 2/6/2026
CREATE TABLE RECUPERAR_SENHA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(120) NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    EXPIRA_EM DATETIME NOT NULL
);

CREATE TABLE FUN_EPI(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	FK_FUNCIONARIO_CPF VARCHAR(14) NOT NULL,
    FK_EPI_ID INT, 
    FOREIGN KEY (FK_FUNCIONARIO_CPF) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE,
    FOREIGN KEY (FK_EPI_ID) REFERENCES EPI(ID) ON DELETE CASCADE
);




-- TESTE
INSERT INTO EMPRESA VALUES ('10.000.000/0001-01','Empresa 1','Rua A','SP','10');
INSERT INTO EMPRESA VALUES ('10.000.000/0002-02','Empresa 2','Rua B','SP','11');


INSERT INTO SETOR VALUES (1,'Setor 1','Bloco A','10.000.000/0001-01');
INSERT INTO SETOR VALUES (2,'Setor 1','Bloco A','10.000.000/0002-02');
-- primeiro insert


INSERT INTO CAMERA VALUES (1,'Ativo','CAM001','10.000.000/0001-01',1);
-- primeiro inser

INSERT INTO ADMINISTRADOR VALUES ('100.000.000-01','Admin 1','1980-01-01','admin1@email.com','(11)90000-0001','adm1', '10.000.000/0001-01');
INSERT INTO ADMINISTRADOR VALUES ('100.000.000-99','Admin 2','1980-01-01','admin2@email.com','(11)90000-0002','adm2', '10.000.000/0002-02');

-- primeiro insert
-- INSERIR NOVO ADM? SIM
INSERT INTO ADMINISTRADOR VALUES ('100.000.000-02','Admin 2','1980-01-01','admin2@email.com','(11)90000-0002','adm2', '10.000.000/0002-02');


INSERT INTO FUNCIONARIO VALUES ('200.000.000-44','Funcionario 2','2000-01-02','f2@email.com','11911110001','f2','RF2','10.000.000/0002-02',2);
-- primeiro insert


INSERT INTO FUNCIONARIO VALUES ('200.000.000-44','Funcionario 2','2000-01-02','f2@email.com','11911110001','12345678','8D F6 DC 06','10.000.000/0002-02',2);


INSERT INTO EPI VALUES (1,'Capacete','img1.png','Proteção cabeça'); 
-- primeiro insert
	
INSERT INTO OCORRENCIA VALUES (1,'2026-03-01','08:00','Capacete','Luva','Irregular',1);
-- primeiro insert

INSERT INTO FUN_OCORRENCIA VALUES (1,'200.000.000-01',1);

INSERT INTO OCORRENCIA_EPI VALUES (1,1,1);

INSERT INTO EPI_ADM VALUES (1,1,'100.000.000-01');

INSERT INTO FUN_ADM VALUES (1,'200.000.000-01','100.000.000-01');

INSERT INTO CAM_ADM VALUES (1, 1, '100.000.000-01');

SELECT * FROM FUNCIONARIO;
SELECT * FROM FUN_EPI;
SELECT * FROM EPI;
SELECT * FROM EMPRESA;
SELECT * FROM CAMERA;


-- Ocorrência de hoje para o funcionário 200.000.000-01
INSERT INTO OCORRENCIA (
    DATA_ANALISE,
    HORA_ANALISE,
    EPIS_DETECTADOS,
    EPIS_AUSENTE,
    STATUS_OCORRENCIA,
    FK_ID_CAMERA
) VALUES (
    '2026-08-11',
    '07:56:00',
    'Capacete',
    'Luva',
    'Irregular',
    1
);

-- Vincula a ocorrência ao funcionário
INSERT INTO FUN_OCORRENCIA (
    FK_FUNCIONARIO_CPF,
    FK_ID_OCORRENCIA
) VALUES (
    '200.000.000-01',
    LAST_INSERT_ID()
);

Select *from epi;


UPDATE FUNCIONARIO
SET SENHA = 'funci123'
WHERE CPF = '200.000.000-44';


CREATE TABLE RFID_SESSAO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_FUNCIONARIO_CPF VARCHAR(14),
    FK_CAMERA_ID INT,
    DATA_HORA DATETIME,
    STATUS VARCHAR(20),

    FOREIGN KEY(FK_FUNCIONARIO_CPF)
    REFERENCES FUNCIONARIO(CPF),

    FOREIGN KEY(FK_CAMERA_ID)
    REFERENCES CAMERA(ID)
);


SELECT
    CPF,
    NOME_COMPLETO,
    EMAIL_CORPORATIVO,
    UID_RFID,
    FK_CNPJ_EMPRESA,
    FK_ID_SETOR
FROM FUNCIONARIO;

Drop TABLE RFID_SESSAO;


UPDATE FUNCIONARIO
SET CPF = '200.000.000-44'
WHERE CPF = '438.875.738-11';



CREATE TABLE IF NOT EXISTS RFID_SESSAO (
    ID INT AUTO_INCREMENT PRIMARY KEY,

    CPF_FUNCIONARIO VARCHAR(14) NOT NULL,

    CAMERA_ID INT NULL,

    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',

    CRIADO_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (CPF_FUNCIONARIO)
        REFERENCES FUNCIONARIO(CPF)
        ON DELETE CASCADE,

    FOREIGN KEY (CAMERA_ID)
        REFERENCES CAMERA(ID)
        ON DELETE SET NULL
);
DELETE FROM FUN_OCORRENCIA;
DELETE FROM OCORRENCIA;